---
apiVersion: v1
kind: Pod
metadata:
  name: pod.ghettolabs.io
  labels:
    app: helloworld
spec:
  containers:
  - name: basicnodeapp
    image: buildmystartup/basicnodeapp
    ports:
    - name: nodejs-port
      containerPort: 3000
